### ISSUE TITLE
Solid-fuel engines can get Transient Failures

### ISSUE THREAD

**Issue by lpgagnon** [ec429/TestLite#10]
...and probably shouldn't. (for example, the GCRC). Possibly other failure types too?

> yeah there's an isSolid = true in those cfgs I should key something off

It's not just about the message, since failure type affects amount of DU. (and then there's the fact that currently many RO solids are re-ignitable with infinite ignitions, but that's not TL's problem)

**Comment by ec429** [comment]
This was fixed by 2f5a0bc6f1fd
