### ISSUE TITLE
testlite issue with new features in testflight

### ISSUE THREAD

**Issue by gmckinnon** [ec429/TestLite#21]
test lite steals the rated burn times from testflight configs but with the addition of continuous burn times this leads to high rated burn times in TL and much slower DU gain as DU is a function of rated burn time.

Non-restartable engines do not have a continuous burn time parameter either so can't just switch to using continuous burn time in TL

**Comment by ec429** [comment]
As of TestLite 0.3.3 we now support `ratedContinuousBurnTime` in addition to `ratedBurnTime`, fixing this.
