### ISSUE TITLE
Could I ask that you include a noticeable attribution to TestFlight?

### ISSUE THREAD

**Issue by jwvanderbeck** [ec429/TestLite#9]
I'm not bitter, really I'm not.  It is unreasonable to expect TestFlight to still be the go-to thing since I no longer maintain it and haven't for years.

That said this mod seems to very, very heavily lean on many of the concepts, designs and even outright data that I spent a very large amount of time creating for TestFlight.

I would very much appreciate a proper attribution rather than a passing reference in the readme.  I kind of feel like I was just tossed under the bus (even bad mouthed in some threads I've seen) without anyone even reaching out to me that I'm aware of.

**Comment by ec429** [comment]
I certainly didn't intend to slight or disparage the great work you did in creating TestFlight.  While I may not agree with all the technical decisions you made in your implementation, and while I have tried to sometimes go beyond, or at least go somewhere else from, what TF did, it's unarguably the case that without TestFlight, TestLite would never have existed.

I will add an 'Acknowledgements' section to the readme to express this.  That there wasn't one already was not malice, merely thoughtlessness.  How would you like to be credited ­— by your github username, as "Agathorn", as "J. W. van der Beck"?

**Comment by jwvanderbeck** [comment]
> That there wasn't one already was not malice, merely thoughtlessness.

I never thought otherwise :)  The disparaging I mentioned was not by you but by some community members but I'm not going to make a deal out of it.

> While I may not agree with all the technical decisions you made in your implementation

That's ok, in hindsight neither do I :)  TestFlight was probably the first large scale mod I ever did and considering that I didn't know anything about modding KSP at the time and was only a novice with Unity I don't judge myself too harshly :)  It was a valuable experience.  Today I work with Unity professionally so I can't complain.

You can credit me as "John Vanderbeck (Agathorn)".  Thank you.

**Comment by ec429** [comment]
Fixed by d49a1c7.
